import os

# Cap computation to on thread
os.environ["OMP_NUM_THREADS"] = "1"
os.environ["OPENBLAS_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["VECLIB_MAXIMUM_THREADS"] = "1"
os.environ["NUMEXPR_NUM_THREADS"] = "1"
import configparser
import gc
import warnings

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")
from datetime import datetime, time, timedelta, timezone
from time import sleep
from zoneinfo import ZoneInfo

import altair as alt
import joblib
import requests
import streamlit as st
from dateutil.relativedelta import relativedelta
from scipy.stats import norm
from xgboost import XGBRegressor

# read in production predictions
all_predictions = pd.read_parquet(
    "./outcomes/results/basketball_nba/basketball_nba_2025.parquet"
)
all_predictions = all_predictions[all_predictions["outcomeStat"].notna()]

st.set_page_config(layout="wide")
st.header("NBA Player Prop Prediction Dashboard (Streamlit)")
st.write("""
This interactive dashboard provides visual analytics for NBA player prop predictions generated by the model pipeline.
Users can select a specific player and view the model’s performance across different prop markets (points, assists, rebounds, threes, blocks, steals) over the past month.

Usage: Ideal for evaluating model performance, identifying trends, and debugging prediction accuracy for individual players.
""")

# View Filter
view = st.radio(
    "Select a View", ["Monthly :chart_with_upwards_trend:", "Game By Game :date:"]
)

# Filter list
players_tuple = tuple(all_predictions["player"].unique())
player_select = st.selectbox("Select a player", options=players_tuple)
previous_view = (datetime.now() - relativedelta(months=1)).date()  # past month
all_predictions = all_predictions[all_predictions["eventDate"] >= previous_view].copy()
full_name_id_select = all_predictions[all_predictions["player"] == player_select][
    "fullNameId"
].iloc[0]

# get player image
path = "./player_images/"
image_folder = os.listdir(path)
fullNameId = (
    full_name_id_select.upper().replace(".", "").replace(" ", "").replace("-", "")
)

image_list = []
for file_name in image_folder:
    full_name_id = (
        file_name[:-4].upper().replace(".", "").replace(" ", "").replace("-", "")
    )
    file_path = path + file_name
    path_and_name_id = [full_name_id, file_path]
    image_list.append(path_and_name_id)

image_df = pd.DataFrame(data=image_list, columns=["fullNameId", "path"])
image = image_df[image_df["fullNameId"] == fullNameId]

if image.empty:
    player_image = image_df[image_df["fullNameId"] == "DOWNLOAD"]["path"].iloc[0]
else:
    player_image = image["path"].iloc[0]

st.image(player_image)


if view == "Monthly :chart_with_upwards_trend:":
    if player_select:
        # Filter for
        filterd_df = all_predictions[all_predictions["player"] == player_select]

        # Pre prep for test scores
        filterd_df["error"] = filterd_df["predictedStat"] - filterd_df["outcomeStat"]
        filterd_df["abs_error"] = abs(filterd_df["error"])

        # Set grids for charts
        col1, col2, col3 = st.columns(3)
        col4, col5, col6 = st.columns(3)

        with col1:
            # compute RMSE, accuracy %
            df_points = filterd_df[filterd_df["market"] == "player_points"]
            if df_points.empty:
                points_rmse = 0
                points_accuracy = 0
            else:
                points_rmse = round(np.sqrt(np.mean(df_points["error"] ** 2)), 2)
                points_accuracy = round(
                    df_points["predictionCorrect"].sum() / len(df_points), 2
                )

            # Set Charts
            st.write("Points predictions")
            st.line_chart(
                df_points[["eventDate", "predictedStat", "outcomeStat", "line"]],
                x="eventDate",
            )
            st.write("RMSE: {}".format(points_rmse))
            st.write("Prediction Rate: {:.0%}".format(points_accuracy))
            st.divider()
        with col2:
            # compute RMSE, accuracy %
            df_threes = filterd_df[filterd_df["market"] == "player_threes"]
            if df_threes.empty:
                threes_rmse = 0
                threes_accuracy = 0
            else:
                threes_rmse = round(np.sqrt(np.mean(df_threes["error"] ** 2)), 2)
                threes_accuracy = round(
                    df_threes["predictionCorrect"].sum() / len(df_threes), 2
                )

            # Set Charts
            st.write("Threes Made predictions")
            st.line_chart(
                df_threes[["eventDate", "predictedStat", "outcomeStat", "line"]],
                x="eventDate",
            )
            st.write("RMSE: {}".format(threes_rmse))
            st.write("Prediction Rate: {:.0%}".format(threes_accuracy))
            st.divider()
        with col3:
            # compute RMSE, accuracy %
            df_assists = filterd_df[filterd_df["market"] == "player_assists"]
            if df_assists.empty:
                assists_rmse = 0
                assists_accuracy = 0
            else:
                assists_rmse = round(np.sqrt(np.mean(df_assists["error"] ** 2)), 2)
                assists_accuracy = round(
                    df_assists["predictionCorrect"].sum() / len(df_assists), 2
                )

            # Set Charts
            st.write("Assists predictions")
            st.line_chart(
                df_assists[["eventDate", "predictedStat", "outcomeStat", "line"]],
                x="eventDate",
            )
            st.write("RMSE: {}".format(assists_rmse))
            st.write("Prediction Rate: {:.0%}".format(assists_accuracy))
            st.divider()
        with col4:
            # compute RMSE, accuracy %
            df_rebounds = filterd_df[filterd_df["market"] == "player_rebounds"]
            if df_rebounds.empty:
                rebounds_rmse = 0
                rebounds_accuracy = 0
            else:
                rebounds_rmse = round(np.sqrt(np.mean(df_rebounds["error"] ** 2)), 2)
                rebounds_accuracy = round(
                    df_rebounds["predictionCorrect"].sum() / len(df_rebounds), 2
                )

            # Set Charts
            st.write("Rebounds predictions")
            st.line_chart(
                df_rebounds[["eventDate", "predictedStat", "outcomeStat", "line"]],
                x="eventDate",
            )
            st.write("RMSE: {}".format(rebounds_rmse))
            st.write("Prediction Rate: {:.0%}".format(rebounds_accuracy))
            st.divider()
        with col5:
            # compute RMSE, accuracy %
            df_blocks = filterd_df[filterd_df["market"] == "player_blocks"]
            if df_blocks.empty:
                blocks_rmse = 0
                blocks_accuracy = 0
            else:
                blocks_rmse = round(np.sqrt(np.mean(df_blocks["error"] ** 2)), 2)
                blocks_accuracy = round(
                    df_blocks["predictionCorrect"].sum() / len(df_blocks), 2
                )

            # Set Charts
            st.write("Blocks predictions")
            st.line_chart(
                df_blocks[["eventDate", "predictedStat", "outcomeStat", "line"]],
                x="eventDate",
            )
            st.write("RMSE: {}".format(blocks_rmse))
            st.write("Prediction Rate: {:.0%}".format(blocks_accuracy))
            st.divider()
        with col6:
            # compute RMSE, accuracy %
            df_steals = filterd_df[filterd_df["market"] == "player_steals"]
            if df_steals.empty:
                steals_rmse = 0
                steals_accuracy = 0
            else:
                steals_rmse = round(np.sqrt(np.mean(df_steals["error"] ** 2)), 2)
                steals_accuracy = round(
                    df_steals["predictionCorrect"].sum() / len(df_steals), 2
                )

            # Set Charts
            st.write("Steals predictions")
            st.line_chart(
                df_steals[["eventDate", "predictedStat", "outcomeStat", "line"]],
                x="eventDate",
            )
            st.write("RMSE: {}".format(steals_rmse))
            st.write("Prediction Rate: {:.0%}".format(steals_accuracy))
            st.divider()

elif view == "Game By Game :date:":
    if player_select:
        # Filter for
        filterd_df = all_predictions[all_predictions["player"] == player_select]

        # Pre prep for test scores
        filterd_df["error"] = filterd_df["predictedStat"] - filterd_df["outcomeStat"]
        filterd_df["abs_error"] = abs(filterd_df["error"])

        # Player game Date list
        game_list = filterd_df["eventDate"].unique()
        date_select = st.selectbox("Select a Game Date:", game_list)

        if date_select:
            filterd_date_df = filterd_df[filterd_df["eventDate"] == date_select]
            st.bar_chart(
                filterd_date_df,
                x="market",
                y=["predictedStat", "outcomeStat"],
                stack=False,
            )
